---
name: Parse all Rawhide specfiles

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    container: quay.io/redhat-user-workloads/fedora-copr-tenant/norpm-testing-image:latest@sha256:9eb585a54fbf0c56316fd02ba0f804fd20962b40e364bcdab1f2557f9c8ba828
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate versions
        run: PYTHONPATH=`pwd` rawhide-tests/parse_epoch_version.py > /our-run.output

      - name: Comparator deps
        run: dnf install -y python3-pyyaml

      - name: Compare results
        run: rawhide-tests/epoch_version_comparator.py /rpmspec.output /our-run.output rawhide-tests/expected.yaml
